mysql:
  path: 127.0.0.1:3306
  config: charset=utf8mb4&parseTime=True&loc=Local
  dbname: better
  username: root
  password: "123456"
  max-idle-conns: 0
  max-open-conns: 0
  log-mode: ""
  log-zap: false
server:
  port: 8888
